name: Main
on:
  # run automatically every hour
  schedule:
    - cron: "0 * * * *"

  # allows to manually run the job at any time
  workflow_dispatch:

  # run on every push on the main branch
  # don't forget to change if you're using 'master' branch
  push:
    branches:
      - main

jobs:
  github-profile-summary-cards:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          BRANCH_NAME: "main"
          UTC_OFFSET: 9
          EXCLUDE: "HTML"
          AUTO_PUSH: true
